### ISSUE TITLE
Add postgres DB to environments

### ISSUE THREAD

**Issue by iliaia** [elijahiakiamsev/123-raiting#1]
Want to have postgres in the project.

**Comment by rusinikita** [comment]
Take neon to skip handling all complexity of self-hosted or managed database.

I use it for bunch of bots and it still free. Write me in telegram for any questions.

https://neon.tech/

**Comment by iliaia** [comment]
@rusinikita thank you for your suggestion, very interestin service. Right now I choosed self-hosted Postgres more for a self-development, than the rational engineering choice.

**Comment by rusinikita** [comment]
Neon is postgres. So all tooling works. In my experience, fancy NoSQL/NewSql need after 1TB of data.
