### ISSUE TITLE
https is working

### ISSUE THREAD

**Issue by iliaia** [elijahiakiamsev/123-raiting#3]
Certificate created.
Certificate added to -express- Ngnix
Redirect from http to https

**Comment by ginn13** [comment]
This can be easily done by Nginx or Traefik.
- No need to tweak Express
- No need to tell Express about new certificates
- Redirects and other stuff are included
- Ready to use tools for free LetsEcrypt certificates

**Comment by iliaia** [comment]
Thank you! Looks like Ngnix is must have knowlege for routing. Will apply to product.

**Comment by iliaia** [comment]
@ginn13 Thank you for the Nginx advice, got the solid solution. Done.
